server:
    port: 3001

spring:
    application:
        name:
            mycloud-coupon

    datasource:
        url: jdbc:mysql://112.124.9.174:3306/mycloud_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: wc
        password: 1140
        driver-class-name: com.mysql.cj.jdbc.Driver

    cloud:
        nacos: 
            discovery:
                server-addr: 
                    112.124.9.174:8848
    redis:
        host: 112.124.9.174
        port: 6381
        password: '000415'
        timeout: 5000


